-- V7__seed_bible_books.sql
-- 성경 66권 기본 데이터 (bible_books)
-- V8 sample qt_passages가 book_id 1(창세기), 19(시편), 43(요한복음)을 참조하므로 선행 필요

-- 구약 39권
INSERT INTO bible_books (id, testament, code, korean_name, english_name, display_order) VALUES
(1,  'OT', 'GEN', '창세기',     'Genesis',         1),
(2,  'OT', 'EXO', '출애굽기',   'Exodus',          2),
(3,  'OT', 'LEV', '레위기',     'Leviticus',       3),
(4,  'OT', 'NUM', '민수기',     'Numbers',         4),
(5,  'OT', 'DEU', '신명기',     'Deuteronomy',     5),
(6,  'OT', 'JOS', '여호수아',   'Joshua',          6),
(7,  'OT', 'JDG', '사사기',     'Judges',          7),
(8,  'OT', 'RUT', '룻기',       'Ruth',            8),
(9,  'OT', '1SA', '사무엘상',   '1 Samuel',        9),
(10, 'OT', '2SA', '사무엘하',   '2 Samuel',       10),
(11, 'OT', '1KI', '열왕기상',   '1 Kings',        11),
(12, 'OT', '2KI', '열왕기하',   '2 Kings',        12),
(13, 'OT', '1CH', '역대상',     '1 Chronicles',   13),
(14, 'OT', '2CH', '역대하',     '2 Chronicles',   14),
(15, 'OT', 'EZR', '에스라',     'Ezra',           15),
(16, 'OT', 'NEH', '느헤미야',   'Nehemiah',       16),
(17, 'OT', 'EST', '에스더',     'Esther',         17),
(18, 'OT', 'JOB', '욥기',       'Job',            18),
(19, 'OT', 'PSA', '시편',       'Psalms',         19),
(20, 'OT', 'PRO', '잠언',       'Proverbs',       20),
(21, 'OT', 'ECC', '전도서',     'Ecclesiastes',   21),
(22, 'OT', 'SNG', '아가',       'Song of Solomon',22),
(23, 'OT', 'ISA', '이사야',     'Isaiah',         23),
(24, 'OT', 'JER', '예레미야',   'Jeremiah',       24),
(25, 'OT', 'LAM', '예레미야애가','Lamentations',   25),
(26, 'OT', 'EZK', '에스겔',     'Ezekiel',        26),
(27, 'OT', 'DAN', '다니엘',     'Daniel',         27),
(28, 'OT', 'HOS', '호세아',     'Hosea',          28),
(29, 'OT', 'JOL', '요엘',       'Joel',           29),
(30, 'OT', 'AMO', '아모스',     'Amos',           30),
(31, 'OT', 'OBA', '오바댜',     'Obadiah',        31),
(32, 'OT', 'JON', '요나',       'Jonah',          32),
(33, 'OT', 'MIC', '미가',       'Micah',          33),
(34, 'OT', 'NAM', '나훔',       'Nahum',          34),
(35, 'OT', 'HAB', '하박국',     'Habakkuk',       35),
(36, 'OT', 'ZEP', '스바냐',     'Zephaniah',      36),
(37, 'OT', 'HAG', '학개',       'Haggai',         37),
(38, 'OT', 'ZEC', '스가랴',     'Zechariah',      38),
(39, 'OT', 'MAL', '말라기',     'Malachi',        39);

-- 신약 27권
INSERT INTO bible_books (id, testament, code, korean_name, english_name, display_order) VALUES
(40, 'NT', 'MAT', '마태복음',   'Matthew',        40),
(41, 'NT', 'MRK', '마가복음',   'Mark',           41),
(42, 'NT', 'LUK', '누가복음',   'Luke',           42),
(43, 'NT', 'JHN', '요한복음',   'John',           43),
(44, 'NT', 'ACT', '사도행전',   'Acts',           44),
(45, 'NT', 'ROM', '로마서',     'Romans',         45),
(46, 'NT', '1CO', '고린도전서', '1 Corinthians',  46),
(47, 'NT', '2CO', '고린도후서', '2 Corinthians',  47),
(48, 'NT', 'GAL', '갈라디아서', 'Galatians',      48),
(49, 'NT', 'EPH', '에베소서',   'Ephesians',      49),
(50, 'NT', 'PHP', '빌립보서',   'Philippians',    50),
(51, 'NT', 'COL', '골로새서',   'Colossians',     51),
(52, 'NT', '1TH', '데살로니가전서','1 Thessalonians',52),
(53, 'NT', '2TH', '데살로니가후서','2 Thessalonians',53),
(54, 'NT', '1TI', '디모데전서', '1 Timothy',      54),
(55, 'NT', '2TI', '디모데후서', '2 Timothy',      55),
(56, 'NT', 'TIT', '디도서',     'Titus',          56),
(57, 'NT', 'PHM', '빌레몬서',   'Philemon',       57),
(58, 'NT', 'HEB', '히브리서',   'Hebrews',        58),
(59, 'NT', 'JAS', '야고보서',   'James',          59),
(60, 'NT', '1PE', '베드로전서', '1 Peter',        60),
(61, 'NT', '2PE', '베드로후서', '2 Peter',        61),
(62, 'NT', '1JN', '요한일서',   '1 John',         62),
(63, 'NT', '2JN', '요한이서',   '2 John',         63),
(64, 'NT', '3JN', '요한삼서',   '3 John',         64),
(65, 'NT', 'JUD', '유다서',     'Jude',           65),
(66, 'NT', 'REV', '요한계시록', 'Revelation',     66);
